# The whole idea was to create confetti using a small .png as the base.
# Gemini suggested the initial movement tech, using velocities and a 'gravity' variable to define the speed.
# Gemini also coded the rotate logic and anything else with comments.

import pygame
import random

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800 # Change to 800 if you want the confetti to disappear.
BACKGROUND_COLOR = (255,255,255)

pygame.init()

screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))

pygame.display.set_caption('image')

sosu_x = 360
sosu_y = 720

COLOR = [
    (255, 213, 0), # Yellow
    (255, 123, 0), # Orange
    (255, 0, 0), # Red
    (255, 0, 140), # Pink
    (136, 0, 255), # Purple
    (0, 21, 255), # Blue
    (0, 170, 255), # Light Blue
    (0, 255, 167), # Green
    (111, 255, 0), # Lime
    (5, 5, 5) # Basically default color
]

class Sosu:
    def __init__(self, sosu_x=400, sosu_y=720): # sosu_x should be 360, but since the rotate code messes with things, the confetti is centered properly at 400.
        self.image = pygame.image.load("sosubleh.png").convert_alpha()
        self.sosu_x = sosu_x
        self.sosu_y = sosu_y

        randomsize = random.randint(45, 85)
        self.image = pygame.transform.scale(self.image, (randomsize, randomsize))

        self.vel_x = random.uniform(-3.3, 3.3)
        self.vel_y = random.uniform(-25, -26)
        self.gravity = random.uniform(0.6, 0.8)
        self.fallgravity = self.gravity - 0.3 # This makes the .png fall slower, mimicking real confetti.

        chosen_color = random.choice(COLOR)
        self.image.fill((chosen_color[0], chosen_color[1], chosen_color[2], 100), special_flags=pygame.BLEND_ADD)

        self.base_image = self.image.copy()
        self.angle = 0
        self.rotate_speed = random.uniform(-3.0, 3.0)

    def move(self):
        if self.sosu_y <= 780:
            self.sosu_x += self.vel_x
            self.sosu_y += self.vel_y

            if self.vel_y < 0:
                self.vel_y += self.gravity
            else:
                self.vel_y += self.fallgravity
                if self.fallgravity > 0.01:
                    self.fallgravity -= random.uniform(0.01, 0.001)

    def rotate(self): # I wanted the confetti to rotate, and I couldn't figure it out with what I know now.
                      # The entire rotation code is thus generated by Gemini.
                      # There were many bugs, and this is the only version that works as intended.
        if self.sosu_y <= 780:
            self.angle = (self.angle + self.rotate_speed) % 360
            self.image = pygame.transform.rotate(self.base_image, self.angle)

        else:
            pass

    def draw(self): # Originally, screen.blit(self.image, (self.sosu_x, self.sosu_y)) was all that stood under this.
                    # Because of the rotate function that caused a lot of errors, Gemini created the code below that works.
        render_x = self.sosu_x - self.image.get_width() / 2
        render_y = self.sosu_y - self.image.get_height() / 2
        screen.blit(self.image, (render_x, render_y))

clock = pygame.time.Clock()

sosu_confetti = [] # To create a lot of instances of Sosu(), I attempted this originally but couldn't get it right. Corrected with Gemini.
for i in range(100):
    sosu_confetti.append(Sosu())

screen.fill(BACKGROUND_COLOR)
pygame.display.flip()
pygame.time.wait(1000)

flag = True
while flag:
    clock.tick(60)
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            flag = False

    screen.fill(BACKGROUND_COLOR)

    for sosu in sosu_confetti:
        sosu.draw()
        sosu.move()
        sosu.rotate()

    pygame.display.flip()

pygame.quit()
exit(0)

# The character in the .png is from a anime. I use 'sosu' to organize things simply because it is a phrase the character often says.
# ദ്ദി◝ ⩊ ◜.ᐟ
